services:
  goclient:
      image: stevengez/goclient_grpc
      container_name: goClient_gRPC
      environment:
        - gRPC_SERVER_IP=host.docker.local
        - gRPC_SERVER_PORT=50051
        - API_GO_PORT=5000
      ports:
        - "5000:5000"