FROM golang:1.18.0-alpine3.15
WORKDIR /go/src/myapp
COPY . .
RUN go get ./
ENV MONGO_DIRECTION=mongodb://admin-g19:so1-fase3@35.232.34.17:27017
ENV REDIS_DIRECTION=34.122.245.240
ENV TIDB_CONNECTION=grupo19:grupo19-f3@tcp(34.123.254.28:4000)/sopes1fase3
ENV RABBIT_DIRECTION=host.docker.internal

CMD ["go","run","main.go"]

#docker build -t rocket1530/subscriber_rabbit .
#docker run -d --name subscriber -e RABBIT_DIRECTION=35.238.6.126 rocket1530/subscriber