services:
  backend: 
    image: stevengez/backendkernel:latest
    container_name: backendKernel
    environment:
      - VM_NAME=1
      - CF_URL=https://us-central1-sopes1-341821.cloudfunctions.net/insertomongo
    ports:
      - "80:5000"
    volumes:
      - /proc:/hostProc
  
  