FROM rust:latest as build
WORKDIR /
COPY . .
ENV MONGO_HOST 10.128.0.20
ENV MONGO_USER admingrupo19
ENV MONGO_PASS so1-fase2
ENV MONGO_DB so-proyecto-f2
ENV MONGO_COLLECTION logs
RUN cargo build

FROM debian:bullseye-slim
WORKDIR /
COPY --from=build ./target/debug/api ./
EXPOSE 8080
CMD ["./api"]