services:
  rabbit:
    image: rabbitmq:3.9.14-alpine
    container_name: messagequeue
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=sopes1
    ports:
      - "5672:5672"
  goserver:
    depends_on:
      - rabbit
    image: stevengez/nodeserver_grpc
    container_name: nodeServer_gRPC
    environment:
      - gRPC_SERVER_PORT=50051
      - RABBIT_SERVER=10.128.0.24 # VM Local IP where Rabbit is running
      - RABBIT_USER=rabbit
      - RABBIT_PASSWORD=sopes1
      - RABBIT_QUEUE=GameQueue
    ports:
      - "50051:50051"
  subscriber:
    depends_on:
      - goserver
    image: stevengez/gorabbit_subscriber
    container_name: rabbitsubscriber
    environment:
      - RABIT_HOST=10.128.0.24 # VM IP where Rabbit is Running
      - RABBIT_PORT=5672
      - RABBIT_QUEUE=GameQueue
      - RABBIT_USER=rabbit
      - RABBIT_PASSWORD=sopes1
      - REDIS_HOST=10.128.0.21 # VM IP where Redis is Running
      - REDIS_PORT=6379
      - MONGO_HOST=10.128.0.20 # VM IP where Mongo is Running
      - MONGO_PORT=27017
      - MONGO_USER=admingrupo19
      - MONGO_PASS=so1-fase2
      - MONGO_DB=so-proyecto-f2
      - MONGO_COLLECTION=logs
      - TiDB_HOST=10.128.0.19 # VM IP where TiDB is Running
      - TiDB_USER=grupo19
      - TiDB_PORT=grupo19-f2
      - TiDB_DB=sopes1f2
    

