runtime: nodejs
env: flex
manual_scaling:
 instances: 1
network:
 session_affinity: true
env_variables:
  TIDB_IP: 34.121.78.30
  TIDB_USER: grupo19
  TIDB_PASS: grupo19-f2
  TIDB_DB: sopes1f2
  REDIS_IP: 34.71.24.199